#ddev-generated

http:
  routers:
    
    
    teraztata-web-80-http:
      
      rule: HostRegexp(`teraztata.ddev.site`)
      
      service: "teraztata-web-80-http"
      tls: false
      entrypoints:
        - http-80
    
    
    teraztata-web-8025-http:
      
      rule: HostRegexp(`teraztata.ddev.site`)
      
      service: "teraztata-web-8025-http"
      tls: false
      entrypoints:
        - http-8025
    
    
    
    
    teraztata-phpmyadmin-80-http:
      
      rule: HostRegexp(`teraztata.ddev.site`)
      
      service: "teraztata-phpmyadmin-80-http"
      tls: false
      entrypoints:
        - http-8036
    
    
    
    
    
    teraztata-web-80-https:
      
      rule: HostRegexp(`teraztata.ddev.site`)
      
      service: "teraztata-web-80-https"
      
      tls: true
      
      entrypoints:
        - http-443
    
    
    teraztata-web-8025-https:
      
      rule: HostRegexp(`teraztata.ddev.site`)
      
      service: "teraztata-web-8025-https"
      
      tls: true
      
      entrypoints:
        - http-8026
    
    
    
    teraztata-phpmyadmin-80-https:
      
      rule: HostRegexp(`teraztata.ddev.site`)
      
      service: "teraztata-phpmyadmin-80-https"
      
      tls: true
      
      entrypoints:
        - http-8037
    
    

  services:
    
    teraztata-web-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-teraztata-web:80
    
    teraztata-web-8025-http:
      loadbalancer:
        servers:
          - url: http://ddev-teraztata-web:8025
    
    teraztata-web-80-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-teraztata-web:80
    
    teraztata-web-8025-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-teraztata-web:8025
    
    teraztata-phpmyadmin-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-teraztata-phpmyadmin:80
    
    teraztata-phpmyadmin-80-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-teraztata-phpmyadmin:80
    


tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/teraztata.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/teraztata.key

